### ISSUE TITLE
Lending Term Onboarding Cannot re-onboard

### ISSUE THREAD

**Issue by ElliotFriedman** [volt-protocol/ethereum-credit-guild#30]
Currently the lending term onboarding contract only supports the addition of a single term at a time. If you ever try to onboard the same asset twice through the contract onboarding contract, it will fail with "Proposal already exists". It seems pretty likely that there would be scenarios where multiple terms are created at the same time and need to be voted on. In this scenario, either users need to vote multiple times, or calldata will need to be generated elsewhere.

To fix the duplicate proposal issue, either the description could have a unique user passed nonce added to the end, or the contract could allow the addition of multiple terms in a user specified order, which would fix this issue iff a proposal contained multiple terms and their order was changed.

**Comment by eswak** [comment]
I don't understand, the "Proposal already exists" should only happen if 2 votes for the same term are created at the same time, but it should be possible to create parallel votes for 2 terms ? Proposal description & calldata is different for each proposed lending term, so the proposalId hash should be unique, too
